### PR TITLE
exfat: Stop using CURRENT_TIME_SEC

### PR DESCRIPTION
**Pull request by cyanogen**
* This is going away in 4.12, replace all instances with
   ktime_get_real_ts64 and timespec64.

### CODE REVIEW

**Comment by dorimanx** [comment]
Before i merge, do all linux builds has all needed functions? As i dont see any kernel ver checks.  Thanks.

**Comment by cyanogen** [comment]
ktime_get_real_ts64 was introduced in 3.17. I can wrap this in a macro.

**Comment by cyanogen** [comment]
This seems to be the right way to go. Turns out CURRENT_TIME_SEC is not y2038 safe either.

**Comment by cyanogen** [comment]
Haven't tested this actually works on an old kernel though, I'll try it out on an Android kernel later tonight.

**Comment by dorimanx** [comment]
Thanks, will be great to get support for all kernels, this driver used from 2.6.x to 4.12.x as of now. Every change, we have to make sure its not braking that.

**Comment by cyanogen** [comment]
There we go. This works on my 4.12-rc4 laptop and my OnePlus 3 (3.18).

**Comment by dorimanx** [comment]
Looks great, thanks for your contribution!

**Pull request merged**
